### ISSUE TITLE
Finalize Bootstrap integration

### ISSUE THREAD

**Issue by thom4parisot** [sudweb/2012#1]
Because currently, **variables** are missing so `type.less` is broken.

**Comment by DirtyF** [comment]
what about upgrading to bootstrap 2.0 to get native responsive features ?

**Comment by thom4parisot** [comment]
Could be a good thing. Foundation is great too (and very simple).

On Thu, Jan 26, 2012 at 11:05 PM, Frank Taillandier <
reply@reply.github.com

> wrote:
> 
> what about upgrading to bootstrap 2.0 to get native responsive features ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/1#issuecomment-3677726

## 

_Thomas PARISOT_
Conseil, dveloppement et performances Web
http://case.oncle-tom.net/  @oncletom http://twitter.com/oncletom
Mobile : +336 08 40 35 49

**Comment by DirtyF** [comment]
The new builder is interesting : 
http://markdotto.com/bs2/docs/download.html
