### ISSUE TITLE
Page should have decent titles

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#101]
The home page has no title element, it's kind of embarassing.

It's the same for all pages, we should have "post-title - website-label" at least on every page.

**Comment by goulvench** [comment]
That's what I said in #69 (including the code), but @oncletom said we should use an SEO plugin instead. We're short on time, let's just use the patch, don't you think?

**Comment by thom4parisot** [comment]
Nope, I add the plugin.

**Comment by thom4parisot** [comment]
Done.
