### ISSUE TITLE
Tagline changed?

### ISSUE THREAD

**Issue by loicm** [sudweb/2012#102]
Our tagline is : "Savoir-faire et faire-savoir".

In the header it has been changed and it shoudn't had too ;) Is there a reason?

**Comment by DirtyF** [comment]
It's a mistake, I'm on it.

On Mon, Mar 12, 2012 at 11:53 AM, Loic Mathaud <
reply@reply.github.com

> wrote:
> 
> Savoir-faire et faire-savoir

## 

Frank Taillandier

**Comment by DirtyF** [comment]
Header updated.
