### ISSUE TITLE
Photo qui fout le camp

### ISSUE THREAD

**Issue by Aymkdn** [sudweb/2012#103]
Nath a repéré que sur http://sudweb.fr/2012/talk/testez-les-recruteurs/ la photo de l'orateur n'était pas du tout au bon endroit....

**Comment by goulvench** [comment]
C'et très probablement parce qu'on récupère la photo de l'orateur. La conf n'ayant pas de photo, elle se retrouve avec la classe `without-thumbnail` ce qui fait que la photo n'est pas bien positionnée.

**Comment by thom4parisot** [comment]
Fixed. Reverted to a state we wanted to avoid.

So right now, we assume to have always a picture for a Talk content. Hints to avoid problems, by order of speed implementation:
- adding a picture for all speakers (some are missing one);
- coding a default thumbnail replacement;
- dig deeper in the thumbnail ID metadata but it's close from a gaz station.

**Comment by DirtyF** [comment]
In case we have no decent picture for a talk, we must provide a default one. We must ask a designer to do this.

**Comment by thom4parisot** [comment]
Otherwise: http://placekitten.com/726/220
