### ISSUE TITLE
Partners thumbnails are resized, resulting in poor quality

### ISSUE THREAD

**Issue by fetard** [sudweb/2012#105]
Partners thumbnails on the bottom of the home page are resized to a 100px width, but the original images are used : so the browser needs to resize it, and the result is a poor image quality.

It should be better to display "pre-resized" thumbnails, using a timthumb-like tool.

**Comment by goulvench** [comment]
Changing assignee, I don't know how to do that.

**Comment by thom4parisot** [comment]
You worked on this part, it was obvious for me you could better understand
the problem than me.

On Mon, Mar 12, 2012 at 1:37 PM, Goulven Champenois <
reply@reply.github.com

> wrote:
> 
> Changing assignee, I don't know how to do that.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/105#issuecomment-4458582

## 

_Thomas PARISOT_
Conseil, dveloppement et performances Web
http://case.oncle-tom.net/  @oncletom http://twitter.com/oncletom
Mobile : +336 08 40 35 49

**Comment by goulvench** [comment]
Weird, [the codex](http://codex.wordpress.org/Function_Reference/add_image_size) says that passing false as 4th argument results in soft (proportional) cropping. Maybe using `set_post_thumbnail_size` messed things up, as studiograsshopper.ch [explains](http://www.studiograsshopper.ch/web-development/wordpress-featured-images-add_image_size-resizing-and-cropping-demo/):

> Avoid using set_post_thumbnail_size() to set your Featured Image display size – to avoid in-browser resizing

**Comment by thom4parisot** [comment]
Or maybe the problem is related that we added the size after uploading the
picture.
I feel that WP has some troubles with that kind of behavior.

On Mon, Mar 12, 2012 at 2:09 PM, Goulven Champenois <
reply@reply.github.com

> wrote:
> 
> Weird, [the codex](http://codex.wordpress.org/Function_Reference/add_image_size) says that
> passing false as 4th argument results in soft (proportional) cropping.
> Maybe using `set_post_thumbnail_size` messed things up, as
> studiograsshopper.ch [explains](http://www.studiograsshopper.ch/web-development/wordpress-featured-images-add_image_size-resizing-and-cropping-demo/):
> 
> > Avoid using set_post_thumbnail_size() to set your Featured Image display
> > size  to avoid in-browser resizing
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/105#issuecomment-4459262

## 

_Thomas PARISOT_
Conseil, dveloppement et performances Web
http://case.oncle-tom.net/  @oncletom http://twitter.com/oncletom
Mobile : +336 08 40 35 49

**Comment by fetard** [comment]
You can resize the thumbnails even if you added a size after the image upload : use the Resize Thumbnails plugin

**Comment by thom4parisot** [comment]
Can you confirm it is better now?

**Comment by samy** [comment]
Yes it is !

**Comment by thom4parisot** [comment]
Cool!
