### ISSUE TITLE
No speaker for a conference? No problem!

### ISSUE THREAD

**Issue by rudyrigot** [sudweb/2012#110]
I added a conference "Question à l'ombre" for the friday night, without a speaker, and the page takes ages to build, before eventually giving up.

When i unpublish the conference, everything goes back to normal.
When i link it to a speaker, everything goes back to normal.
So, yeah, the problem definitely comes from the missing link.

To do : accept to list and show a speakerless conference ; and delete that freaking "Tous les orateurs !" speaker from the wordpress online.

**Comment by thom4parisot** [comment]
It should be ok. Please close the issue if so.

**Comment by rudyrigot** [comment]
Well, from what i see, someone did it already, and it's working greatly.

End of story! :)
