### ISSUE TITLE
Contact form failed to send message

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#111]
http://sudweb.fr/2012/contact/

When I try to send a message when I'm not connected on the Wordpress, I get this message :

Failed to send your message. Please try later or contact the administrator by another method.

**Comment by MoOx** [comment]
plugin wp contact form 7 ?
Y'aura pas un champ obligatoire en trop ? genre user id ou un truc du genre ?

**Comment by DirtyF** [comment]
Le formulaire part bien quand on est connecté à l'admin, mais échoue si on est pas authentifié

**Comment by thom4parisot** [comment]
Rectifié ; c'était lié à Hyper Cache.

Solution : raccourcir la durée du cache.
En étant connecté ça posait pas de soucis puisque le cache est désactivé dans ce cas de figure.
