### ISSUE TITLE
Maximum distances from hotels to venue(s)

### ISSUE THREAD

**Issue by brunobord** [sudweb/2012#113]
give people indications on "how far the hotels are from/to the two different venues"

**Comment by brunobord** [comment]
(patch is on the way...)

**Comment by brunobord** [comment]
forme: Hotel distance Vendredi distance Samedi
- Baragnon : **V: 850m**, S: 1,3km
- Excelsior : V: 1km, **S: 650m**
- Chartreuse : V: 1km, **S:500m**
- Ours blanc : V: 400m, **S: 290m**
- H. Sainte-Claire : **V: 1,4km**, S: 2km
- Castellane : **V: 600m**, S: 700m
- Royal Wilson : **V: 550m**, S: 750m
- Héliot : V: 700m, **S: 350m**
- Victor Hugo : V: 400m, **S: 290m**
- Capitôle Hôtel: **V: 68m**, S: 500m
- Albion : V: 800m, **S: 400m**
- Patio Wilson : V: 450m, **S: 300m**
- Beaux-arts : **V: 900m**, S: 1,5km
- Clocher de Rodez : V: 400m, **S: 200m**
- Albert 1er : **V: 50m**, S: 500m
- Mercure Saint Georges : **V: 550m**, S: 800m
- Raymond IV : V: 550m, **S: 280m**
- Riquet : V: 1.1km, **S: 650m**
- Le Cousture : **V: 600m**, S: 750m
- Saint-Sernin : **V: 450m, S: 450m**
- Citiz Hôtel : **V: 500m**, S: 550m
- Opéra : **V: 190m**, S: 750m
- Balcon : **V: 190m**, S: 750m

**Comment by DirtyF** [comment]
Thank you Sir Bruno, we'll see how to add this on the page.

**Comment by thom4parisot** [comment]
The best would be to have a table with 1 row per hotel and 1 column per information.

<table>
  <thead>
  <tr>
    <th>Étoiles</th>
    <th>Hôtel</th>
    <th>Adresse</th>
    <th>Distance vers journée du vendredi</th>
    <th>Distance vers journée du samedi</th>
  </tr>
  </thead>
  <tbody>
    <tr>
      <td>1 étoile</td>
      <td>Hôtel Croix Baragnon</td>
      <td>17 rue Croix Baragnon</td>
      <td>850m</td>
      <td>1,3km</td>
    </tr>
  </tbody>
</table>

**Comment by DirtyF** [comment]
updated the page http://sudweb.fr/2012/comment-venir/dormir-a-toulouse/
