### ISSUE TITLE
Enhance sponsor pages (logo and title)

### ISSUE THREAD

**Issue by loicm** [sudweb/2012#119]
Actually sponsors pages are buggy, see : http://sudweb.fr/2012/sponsor/open-studio/

We need wether to delete the title or move it so as it will not be over the logo anymore.

**Comment by thom4parisot** [comment]
OK, this is due to the fact we use the same layout as any other content.

Do we have to display the logo according to the level of sponsoring?

**Comment by loicm** [comment]
On theses pages we display the logo for every sponsor. No need to adapt according the level of sponsoring.

**Comment by goulvench** [comment]
Done, see pull request #123
