### ISSUE TITLE
deuxième conférence sur la home

### ISSUE THREAD

**Issue by desbenoit** [sudweb/2012#129]
Est-il possible d'afficher une seconde conférence sur la home pour équilibre avec l'actualité ? Merci :)

**Comment by DirtyF** [comment]
On pourrait en effet afficher une conférence et un laboratoire

2012/3/27 desbenoit <
reply@reply.github.com

> Est-il possible d'afficher une seconde conférence sur la home pour
> équilibre avec l'actualité ? Merci :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/129

## 

Frank Taillandier

**Comment by desbenoit** [comment]
Ce serait top !

**Comment by thom4parisot** [comment]
Le plus rapide pour l'instant est d'en afficher 2.

Je ne me souviens plus si ça avait été facile de requêter sur des critères supplémentaires (type la journée).
J'imagine que c'est de l'ordre du possible ;-)

**Comment by DirtyF** [comment]
Encore plus rapide n'afficher qu'une actualité ;) 

@oncletom attention j'ai fait ça en live pendant le conf call en éditant directement le fichier sur Github

**Comment by thom4parisot** [comment]
Bon en fait on pouvait clôturer.
