### ISSUE TITLE
Favicon could look better

### ISSUE THREAD

**Issue by rik** [sudweb/2012#132]
The current favicon has some ugly white borders. It could look way better without those.

**Comment by goulvench** [comment]
At least it doesn't weigh 400k ;-)

We'll look into that, as time allows.

**Comment by DirtyF** [comment]
Removed white borders, now it's looks better indeed :
http://cl.ly/2o3A3O121g101n072U2U

**Comment by rik** [comment]
Thanks. I think the favicon would greatly benefit from alpha transparency. Either with a PNG or ICO file.
http://stackoverflow.com/questions/1344122/favicon-png-vs-favicon-ico-why-should-i-use-pngs-instead-of-icos

This is really a nitpick though. Anyway, I learned about alpha transparency support in .ico files.

**Comment by rik** [comment]
I really meant to link to http://stackoverflow.com/a/1344379

**Comment by DirtyF** [comment]
@Rik http://sudweb.fr/favicon.ico and http://sudweb.fr/favicon.png have alpha transparency
