### ISSUE TITLE
Faux-bold sur certains titres

### ISSUE THREAD

**Issue by fvsch** [sudweb/2012#137]
La deuxième règle `@font-face` dans `wp-sudweb-theme/assets/fonts/din-alternatebold/stylesheet.css` déclare une fonte Bold comme `font-weight:normal`.

Par conséquent, lorsque cette fonte est utilisée pour un texte en `font-weight:bold`, certains navigateurs et OS vont fabriquer du faux-bold à la laideur plus ou moins prononcée. C’est le cas sur Mac avec Opera, Firefox et Chrome, par exemple. On peut voir le problème sur http://sudweb.fr/2012/comment-venir/ ou http://sudweb.fr/2012/actualites/

Solution: déclarer un `font-weight:bold` dans la règle `@font-face`.
Si jamais cela posait problème à certains navigateurs (IE9 peut-être? ou de vieilles versions d'Opera ou Safari?), la solution techniquement fausse mais pragmatique consiste à s'assurer que quand on utilise cette fonte custom on veille bien à ne jamais déclarer de `font-weight:bold`. Mais c'est le genre de truc à en oublier dans les coins.

**Comment by rik** [comment]
Tu peux proposer un patch ? :)

**Comment by fvsch** [comment]
Non, parce que je n’aurai pas le temps de tester et/ou me documenter, pour savoir laquelle des deux solutions proposées est pertinente.
