### ISSUE TITLE
Restez informer : contenu 

### ISSUE THREAD

**Issue by desbenoit** [sudweb/2012#15]
Le lien enveloppe doit avoir la mention "Newsletter" et doit pointer vers http://sudweb.us2.list-manage.com/subscribe 
Merci !

**Comment by thom4parisot** [comment]
Ce lien renvoie vers une page 404. Tu pourrais me passer un lien qui continue à fonctionner dans le temps ?

**Comment by desbenoit** [comment]
Cela devrait sans doute mieux marcher avec cela. http://eepurl.com/dKjaE

**Comment by DirtyF** [comment]
Menu réseaux mis à jour.
