### ISSUE TITLE
Restez informer : forme

### ISSUE THREAD

**Issue by desbenoit** [sudweb/2012#16]
Répartir horizontalement les éléments du restez informer. 

Merci !

**Comment by thom4parisot** [comment]
OK pour toi @desbenoit ?

**Comment by desbenoit** [comment]
Le soulignement de survol devient un surlignement sur les flêches newsletter, twitter, lanyrd et google+ 

Je me suis mal exprimé pour l'horizontal : est-il possible d'harmoniser les marges entre tous les éléments de manière à ce que le dernier (google plus) soit à une marge équivalente du bord que le premier ?

**Comment by goulvench** [comment]
@desbenoit j'ai un correctif pour le soulignement qui devient surlignement. Pour l'alignement horizontal, à quel largeur écran veux-tu que l'alignement soit différent, quand c'est sur fond jaune, ou quand le site s'affiche en plus de 940px ?

**Comment by desbenoit** [comment]
Merci ! 

Quand c'est en plus de 940 s'il te plait.

Le 5 mars 2012  04:12, Goulven Champenois a crit :

> @desbenoit j'ai un correctif pour le soulignement qui devient surlignement. Pour l'alignement horizontal,  quel largeur cran veux-tu que l'alignement soit diffrent, quand c'est sur fond jaune, ou quand le site s'affiche en plus de 940px ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/16#issuecomment-4316098

## 

Sbastien Desbenoit
twitter :  @desbenoit
blog : http://internetetmoi.fr
mobile :  +33 (0)6 98 54 92 93
