### ISSUE TITLE
Ajouter deux champs "Heure début" et "Heure fin" sur le type de données "Conférence"

### ISSUE THREAD

**Issue by rudyrigot** [sudweb/2012#18]
Je pense que c'est pas la peine de mettre un jour, puisqu'il dépend du type de conférence (qui est déjà contribuable)

**Comment by goulvench** [comment]
Ce n'est pas la peine pour nous mais si on passe sur 2 jours de
confrences, on en aurait besoin. J'avais pens utiliser les catgories

## Wordpress pour lister les confrences d'un jour particulier sinon.

Goulven Champenois

2012/2/26 Rudy Rigot <
reply@reply.github.com

**Comment by rudyrigot** [comment]
Ah bah, bien vu ! :)

## 

2012/2/27 goulvench <
reply@reply.github.com

**Comment by thom4parisot** [comment]
On est dj sur 2 jours d'vnements.

Dans la page programme, on a besoin de pouvoir lister ce qu'il se passe le
vendredi, et le samedi.
Par contre on n'a pas besoin de l'heure de fin : a dpend du format  et
comme pour l'instant au niveau des labos on s'en fiche puisqu'on les
indiquera  titre informatif, a va.

2012/2/27 goulvench <
reply@reply.github.com

> Ce n'est pas la peine pour nous mais si on passe sur 2 jours de
> confrences, on en aurait besoin. J'avais pens utiliser les catgories
> 
> ## Wordpress pour lister les confrences d'un jour particulier sinon.
> 
> Goulven Champenois
> 
> 2012/2/26 Rudy Rigot <
> reply@reply.github.com
> 
> > Je pense que c'est pas la peine de mettre un jour, puisqu'il dpend du
> > type de confrence (qui est dj contribuable)
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/sudweb/wp-sudweb-theme/issues/18
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/18#issuecomment-4190219

## 

_Thomas PARISOT_
Conseil, dveloppement et performances Web
http://case.oncle-tom.net/  @oncletom http://twitter.com/oncletom
Mobile : +336 08 40 35 49

**Comment by thom4parisot** [comment]
Ah ben la réponse par mail fait sauter les accents. bonjourunicode.com !

**Comment by rudyrigot** [comment]
Oui, oui, 2 jours d'vnements, mais un jour de _confrence_ ; du coup je
disais qu'on pouvait diffrencier sur le type de sance, mais Goulven a
raison : le jour o on a 2 jours de _confrence_, le systme est caduque.

Par contre, bien vu pour l'heure de fin, je vous laisse voir, du coup.

## 

2012/2/27 Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
Ça coûte pas grand chose en fait : j'ai créé un type de contenu "Journée", parce qu'on s'est rendu compte avec Frank que chaque jour se passe dans un lieu différent.

Et itou pour la soirée communautaire en fait, qui est un élément de programme (journée) associée à un lieu (inconnu encore).

**Comment by rudyrigot** [comment]
Ok, not.

2012/2/27 Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
Y'a un champ "Heure de début". Et y'a un autre champ "journée", donc.

En ligne !
