### ISSUE TITLE
Mettre en ligne le type "Orateur", en ajouter un champ au type de données "Conférence"

### ISSUE THREAD

**Issue by rudyrigot** [sudweb/2012#19]

**Comment by thom4parisot** [comment]
Yo @rudyrigot, c'est mis. Tu trouveras une boîte "Orateurs" (Speaker pqu'y a pas encore la traduction) à côté de chaque page d'admin des conférences). Et tu peux en choisir plusieurs !

**Comment by rudyrigot** [comment]
J'allais faire, mais je vois que ça a déjà été fait !

**Comment by thom4parisot** [comment]
Pas sur tous je crois ... Je me suis arrt  la moiti.
Le 1 mars 2012 20:18, "Rudy Rigot" <
reply@reply.github.com>
a crit :

**Comment by thom4parisot** [comment]
@DirtyF a terminé l'action pendant le point hebdo hier. Tu confirmes (et t'as récupéré ta tondeuse) ?

**Comment by DirtyF** [comment]
Toutes les conférences ont été relié avec des orateurs.

Et oui j'ai bien récupéré ma tondeuse, c'est fou comme un petit affutage de lame change la vie.

**Comment by rudyrigot** [comment]
Juste histoire d'avoir une deuxième paire d'yeux, je referai un passage entier ce week-end sur toutes les contribs Speakers / Conférences dans le week-end, pour être sûr que tout est à jour par rapport à tous les mails qu'on a reçu (parce qu'il y en a tellement eu d'un coup, que je suis un peu paumé)

**Comment by thom4parisot** [comment]
Ça roule.

Pour info, j'ai saisi deux orateurs (Pablo et Rachel) pour montrer l'exemple.
Les vignettes sont automatiquement retaillées en fonction des endroits où elles sont utilisées.

**Comment by DirtyF** [comment]
du coup ça donne des résultats un peu space : 
http://sudweb.fr/2012/speaker/pablo-pernot/
