### ISSUE TITLE
Développer la page "Sponsors"

### ISSUE THREAD

**Issue by rudyrigot** [sudweb/2012#20]
Pour l'instant, y'a que la nav ! :)

**Comment by thom4parisot** [comment]
@desbenoit , il y a une présentation spécifique pour cette page ?

**Comment by desbenoit** [comment]
Je la prépare dans la seconde !

**Comment by thom4parisot** [comment]
Je génère le code. Ça serait super cool si @goulvench pouvait faire la partie CSS !

**Comment by thom4parisot** [comment]
Bon en fait j'avais pas les yeux en face des trous. C'est en ligne.
