### ISSUE TITLE
Participer

### ISSUE THREAD

**Issue by desbenoit** [sudweb/2012#21]
Diviser la "page" participer actuelle en une page d'accueil + des sous-pages : 

M'inscrire

Convaincre mon boss

Venir à Toulouse

Venir à Sud Web (Tout vers une même page avec des ancres pour les différents lieux) 
- Le vendredi : Salle du Sénéchal 
- Le vendredi soir : Repas communautaire
- Le Samedi : Epitech Toulouse

Dormir à Toulouse

Merci !

**Comment by DirtyF** [comment]
M'inscrire c'est pas la même page que description on est d'accord ?

**Comment by DirtyF** [comment]
Les pages ont été crées et le contenu de la page Participer a été migré dans la page Venir à Toulouse.

**Comment by thom4parisot** [comment]
Ça peut être géré uniquement comme du contenu via l'admin de WordPress, vous me confirmez ?

**Comment by desbenoit** [comment]
Euh, on a un soucis, je ne vois plus le sous menu de participer dans participer mais celui de programme :/

**Comment by desbenoit** [comment]
Maintenant est-il possible d'utiliser plutôt le style des sous-items ? je trouve que les pavés sont vraiment lourds

**Comment by goulvench** [comment]
J'ai raccourcit le texte du lien dans le menu (tout en le laissant tel quel dans le titre), il tient maintenant sur 2 lignes. Ça te va comme ça ?

**Comment by DirtyF** [comment]
Moi ça me va très bien ;)

**Comment by desbenoit** [comment]
Merci =)
