### ISSUE TITLE
Define the language of a talk

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#23]
One can be able to specify the language of a given talk

**Comment by goulvench** [comment]
If we don't translate the speaker descriptions, we need to also be able to tell what language it's in.

**Comment by DirtyF** [comment]
@goulvench I don't get it it's written in plain text on the page in the meta of the article 
example : http://sudweb.fr/2012/talk/from-service-provider-to-software-vendor/

**Comment by goulvench** [comment]
Just added to the interface using custom fields. If I make it mandatory Wordpress refuses to save the post, strange.
We need to put this information in the HTML.

**Comment by thom4parisot** [comment]
I don't get the point on what you wanted @goulvench: there was already a language field.
If you talk about adding the language spoken by the speaker, for the speaker page, sorry but it's another issue. The title of this one is **language** + **talk**
