### ISSUE TITLE
Analytics tracking

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#24]
Don't forget to add the Google Analytics code tracking before going online.

It could be done the simplest way or with this lind of plugin :
http://wordpress.org/extend/plugins/google-analytics-for-wordpress/

**Comment by thom4parisot** [comment]
This is definitely a good plugin. You can install and configure it with the proper credentials (it uses OAuth to link GA account and the blog – no more UA copy/paste anymore).

**Comment by DirtyF** [comment]
OK I installed the plugin. I'll look into the config tonight.
