### ISSUE TITLE
Conférence multi-formats : 1 ou plusieurs conf' ?

### ISSUE THREAD

**Issue by thom4parisot** [sudweb/2012#27]
Quand une conf' est retenue pour un LT et un labo, qu'est-ce qu'on fait :
- 1 contenu associé à LT et Labo ?
- 1 contenu associé à LT et 1 contenu associé à Labo ?

**Comment by thom4parisot** [comment]
Hein @DirtyF, @rudyrigot, @desbenoit ou @loicm ?

**Comment by desbenoit** [comment]
1 contenu associé LT + 1 Labo IMHO

**Comment by loicm** [comment]
J'aurais plutôt vu ça sous 2 contenus différents car ce sont 2 sessions différentes avec des description et contenu différents.

**Comment by rudyrigot** [comment]
Ouep, 2 contenus pour moi, chacun avec un lien vers l'autre, pourquoi pas.

Il y a de quoi expliquer la pertinence de chacun diffremment.

## 

2012/2/27 desbenoit <
reply@reply.github.com

**Comment by DirtyF** [comment]
Pareil que @loicm

**Comment by thom4parisot** [comment]
OK merci ! 1 conf par format donc.

**Comment by goulvench** [comment]
Je pencherai pour un contenu par format, avec des liens entre les 2. a

## simplifiera l'affichage d'une navigation "confrence prcdente/suivante".

Goulven Champenois

2012/2/27 Oncle Tom <
reply@reply.github.com
