### ISSUE TITLE
Page Programme

### ISSUE THREAD

**Issue by thom4parisot** [sudweb/2012#33]
@goulvench tu peux t'occuper de l'intégration ?

De mon côté je me chargerai de rendre ça dynamique en générant ce qu'il faut via WordPress.

Merci :-)

**Comment by thom4parisot** [comment]
Le contenu est généré.

**Comment by goulvench** [comment]
Cool, je rcupre a et je colle les styles dessus. J'avais presque termin
mais je n'tais pas sr de comment a allait tre possible de gnrer a,

## notamment le double-track.

Goulven Champenois

On Fri, Mar 2, 2012 at 12:21 PM, Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
C'est dans ma branche `speaker` ; je la merge sur le master pour que tu la récupères plus facilement. – et c'est fait !

**Comment by thom4parisot** [comment]
Au passage, j'ai installé un plugin de sauvegarde de base de données. Ça facilite la création de dumps pour les importer en local.
