### ISSUE TITLE
Fix link to sponsorship file

### ISSUE THREAD

**Issue by goulvench** [sudweb/2012#37]
Current link has # for a href

**Comment by thom4parisot** [comment]
Solution: Admin > Media > Upload the sponsorship file.

Then copy/paste its URL in the menu, as a replacement for `#`.

**Comment by goulvench** [comment]
Yes, but how to avoid hardcoding this URL into the theme? Using theme

## options http://codex.wordpress.org/Theme_Development#Theme_Options?

Goulven Champenois

On Fri, Mar 2, 2012 at 2:24 PM, Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
It will be hardcoded too as a database setting.

The only thing which is interesting this way is we would manage the file and its (implicit) URL in the same one place.
For now, it's quicker to do "my way". We can improve it later with a theme option.

**Comment by loicm** [comment]
File uploaded, its URL is : http://sudweb.fr/2012/wp-content/uploads/2012/03/dossier-partenariat-2012.pdf

I can set the URL in the theme but I think it's not the way Thomas wanted us to do?

**Comment by thom4parisot** [comment]
Ah ok j'avais pas vu en fait que c'était hardcodé dans le thème … je pensais que c'était un élément de menu. Mea culpa (je comprends mieux la remarque de Goulven).

On fait comme ça pour l'instant, même si c'est pas beau.
