### ISSUE TITLE
Display sponsor's logos

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#40]

**Comment by goulvench** [comment]
Use the featured image in each post

**Comment by goulvench** [comment]
We need to uncrop the logo though

**Comment by thom4parisot** [comment]
Au besoin, tu peux créer un format supplémentaire type (`sponsor-logo`) dans `functions.php` (y'a déjà un exemple) et l'appeler avec `the_post_thumbnail('sponsor-logo')`. Le troisième paramètre permet de cropper (ou pas) le logo.

**Comment by DirtyF** [comment]
Si j'ai bien suivi j'ai donc ajouté dans le fichier 

add_image_size('sponsor-logo', 150, 150, false);

**Comment by thom4parisot** [comment]
Bah si c'est pour du 150x150, c'est la taille par défaut du format `thumbnail` (valeur par défaut ou que j'ai mise dans Réglages > Médias) – sous-entendu, y'aurait même pas besoin de la créer.

**Comment by DirtyF** [comment]
J'ai pas vraiment regarder la taille de vignette qu'il fallait générer,
c'était surtout pour éviter le recordage automatique de la photo.
Maintenant je sais comment ça marche, si on doit changer la taille, on la
changera.

2012/3/4 Oncle Tom <
reply@reply.github.com

> Bah si c'est pour du 150x150, c'est la taille par défaut du format
> `thumbnail` (valeur par défaut ou que j'ai mise dans Réglages > Médias)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/40#issuecomment-4307217

## 

Frank Taillandier
