### ISSUE TITLE
Add image in the header

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#41]

**Comment by rudyrigot** [comment]
Bon, ok, j'ai tenté des trucs avec JS fiddle, et si on est ok pour que le faire en JS soit acceptable, voila ce que ça donne : http://jsfiddle.net/rudyrigot/kFqSj/25/

(j'espère que c'est JS fiddle qui merde et pas l'API flickr, mais parfois, il faut faire "Run" ou Ctrl+S plusieurs fois pour que ça marche)

Par contre --> on ne peut pas contraindre une taille, on ne peut que prendre une d'origine de Flickr ; j'ai mis celle qui était la plus proche de notre besoin.

**Comment by thom4parisot** [comment]
J'ai mis à jour le Fiddle, pour corriger le bug : le total est supérieur au nombre de photos retournées (tronqué à 100).

**Comment by rudyrigot** [comment]
Cool, merci !

**Comment by DirtyF** [comment]
encore plus top si on peut limiter à un album car je suis pas sur que
d'afficher les photos de la soirée pizza soit pertinent.

On Fri, Mar 2, 2012 at 12:24 PM, Rudy Rigot <
reply@reply.github.com

> wrote:
> 
> Cool, merci !
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/41#issuecomment-4284067

## 

Frank Taillandier

**Comment by thom4parisot** [comment]
On veut afficher les photos prises par les participants de Sud Web ?

**Comment by rudyrigot** [comment]
Tout a est possible facilement avec l'API FlickR :
http://www.flickr.com/services/api/

Il suffit de dcider :
1. toutes les photos prises par SudWeb ?
2. toutes les photos prises par SudWeb dans l'album "Confrences"
   seulement
3. ou toutes les photos prises par tout le monde, et avec "sudweb" ou
   "sudweb2011" comme tag

Dites-moi ce que vous voulez, et je modifierai le JS fiddle en fonction.

## 

On Fri, Mar 2, 2012 at 4:18 PM, Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
Fait : drivé par microdata.

**Comment by DirtyF** [comment]
Rudy,

Je suis d'avis de partir d'abord sur les photos des confs de Thanh.

L'ID du set des conférence est 72157627495399296 (http://www.flickr.com/photos/sudweb/sets/72157627495399296/)

Il me semble qu'il faut faire appel à cette méthode
http://www.flickr.com/services/api/flickr.photosets.getPhotos.html

**Comment by rudyrigot** [comment]
Fait dans le JSFiddle : http://jsfiddle.net/rudyrigot/kFqSj/36/

Ce qui a changé :
- j'ai implémenté ta correction d'erreur ("total" remplacé par "photo.length")
- remplacé le "var userId" par un "var photosetId" qui va être plus utile pour notre cas (du coup, à remplacer dans vos microdata, j'imagine)
- remplacé la valeur de la var "url", du coup
- et remplacé tous les "data.photos" par "data.photoset"

L'URL appelée doit donner ça, en fait : http://api.flickr.com/services/rest/?format=json&method=flickr.photosets.getPhotos&api_key=b3acf3ad86fbd88dc1def300e94f9448&photoset_id=72157627495399296&jsoncallback=?

**Comment by loicm** [comment]
Si c'est que ça je vous review++ car ça marche plutôt bien :)
