### ISSUE TITLE
Missing lang attribute when talk/speaker descriptions are not in the site language

### ISSUE THREAD

**Issue by goulvench** [sudweb/2012#50]

**Comment by thom4parisot** [comment]
Done, but can't commit through airport Wi-Fi.

**Comment by thom4parisot** [comment]
C'est fait, et mis en ligne ! Tu me confirmeras que ça correspond ?

**Comment by goulvench** [comment]
Je vois bien les attributs dans le code source, mais ils sont vides. Il
devraient contenir `fr` ou `en`. D'ailleurs il faut le mettre  chaque fois
que le titre et la description d'un lment anglais est affich (en liste
dans le programme, en alatoire sur la home).

Je ne sais pas ce qui peut bloquer, peut-tre la rcupration de

## l'identifiant de post ?

Goulven Champenois

On Sun, Mar 4, 2012 at 4:32 AM, Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
Ils sont vides parce qu'ils n'ont pas dû être renseignés du côté de la conf.

**Comment by loicm** [comment]
Je ne vois pas où cela doit être renseigné, tu peux me donner l'indication Thomas ? Je peux m'occuper de saisir ensuite chaque langue pour chaque conférence.

**Comment by goulvench** [comment]
C'est fait, je pense que ça ne s'affichait pas parce qu'on a rajouté le champ après avoir saisi les contenus, et la récupération du champ ne trouvait pas de données en base.

**Comment by thom4parisot** [comment]
C'est exactement ça :-) Merci !
