### ISSUE TITLE
Sponsors Listing broken

### ISSUE THREAD

**Issue by thom4parisot** [sudweb/2012#59]
Sponsors listing at the bottom of the page is broken: they seem to float on the right.

Can be seen on: http://sudweb.fr/2012/

cc @DirtyF

**Comment by DirtyF** [comment]
I think It's relative to the merge I did yesterday https://github.com/sudweb/wp-sudweb-theme/pull/55

**Comment by thom4parisot** [comment]
@goulvench, some review is needed please.

**Comment by goulvench** [comment]
The layout looked odd with the current number of sponsors (it wasn't broken though). This has been corrected in issue #73 by using the sponsor list page layout instead.

**Comment by desbenoit** [comment]
Ok for me. Good work !
