### ISSUE TITLE
Missing margins on thumbnails

### ISSUE THREAD

**Issue by thom4parisot** [sudweb/2012#60]
As seen on: http://sudweb.fr/2012/programme/

Right margin should be equal to left margin.

**Comment by goulvench** [comment]
That's because they're absolutely positioned, they can't shift content around.

@desbenoit: Do these images have to be larger than those on the schedule page, http://sudweb.fr/2012/schedule/conferences/ (150 by 150 instead of 60 by 60)?

**Comment by desbenoit** [comment]
Yes, i'd like too. 

Is it possible to split in two columns? 

Le 5 mars 2012  20:04, Goulven Champenois a crit :

> That's because they're absolutely positioned, they can't shift content around.
> 
> @desbenoit: Do these images have to be larger than those on the schedule page, http://sudweb.fr/2012/schedule/conferences/ (150 by 150 instead of 60 by 60)?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/60#issuecomment-4329324

## 

Sbastien Desbenoit
twitter :  @desbenoit
blog : http://internetetmoi.fr
mobile :  +33 (0)6 98 54 92 93

**Comment by thom4parisot** [comment]
As @goulvench pointed out previously, splitting in 2 columns a single track chronological schedule may cause reading difficulties.

@goulvench maybe the easiest way is to add a CSS class on the block container, to know how much margin title + content should have.

**Comment by desbenoit** [comment]
Du coup, je trouve la mise en page que j'ai fait super lourde. Je pense qu'il faudrait supprimer les barres rouges et jaunes.

**Comment by goulvench** [comment]
On peut réduire la barre rouge si tu veux, par exemple descendre de 10 à 7px.

**Comment by desbenoit** [comment]
Ce serait déjà bien.

**Comment by thom4parisot** [comment]
Est-ce qu'il y a d'autres choses à faire ? @desbenoit c'est toi notre patte créative ;-)

**Comment by desbenoit** [comment]
Si c'est possible, j'aimerai vraiment que l'on supprime les barres jaunes. En gardant les mêmes interblocs (i.e. rajouter la largeur de la bande jaune dans la marge)
