### ISSUE TITLE
Interlignage

### ISSUE THREAD

**Issue by desbenoit** [sudweb/2012#64]
Je suis en train de regarder que j'avais baser l'alignement horizontal des textes et du coup les interlignages sur une grille. Est-il possible de reproduire cela sur le site. (au moins sur les pages de contenus). 

Si c'est trop chronophage, est-il possible de pousser l'interlignage des textes de contenus ?

**Comment by DirtyF** [comment]
@desbenoit si je prend une page de contenu je vois que la police est en 16px et l'interlignage en 19px soit un ratio d'1.1875, on le passe à 1.4 ?

**Comment by desbenoit** [comment]
S'il te plait. 

Le 5 mars 2012  22:14, Frank Taillandier a crit :

> @desbenoit si je prend une page de contenu je vois que la police est en 16px et l'interlignage en 19px soit un ratio d'1.1875, on le passe  1.4 ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/64#issuecomment-4331950

## 

Sbastien Desbenoit
twitter :  @desbenoit
blog : http://internetetmoi.fr
mobile :  +33 (0)6 98 54 92 93

**Comment by DirtyF** [comment]
J'ai touché uniquement au texte dans les paragraphes du contenu principal, ça améliore déjà pas mal les choses.

**Comment by thom4parisot** [comment]
Pour référence, commit b2935fb.

**Comment by desbenoit** [comment]
Merci !
