### ISSUE TITLE
Page content below the fold on netbooks

### ISSUE THREAD

**Issue by goulvench** [sudweb/2012#67]
On most netbooks, and on iPads in landscape mode too, the header is so tall that it fills the entire window, and page contents sits just below the fold. Oops.

We should maybe restrict the breakpoint "over 600" to screens taller than 600 pixels too.

**Comment by thom4parisot** [comment]
I propose to fix that after launch because it implies some redesign.

**Comment by goulvench** [comment]
Having rearranged the header during last night's conference code, it looks like we only need to tweak the pitch and call-to-action placement to reclaim some real estate. @desbenoit, want to look at it yourself or do you prefer that we try it out in a branch and show you what that might look like?

**Comment by thom4parisot** [comment]
Perfect. Let's focus on the website launch though.
