### ISSUE TITLE
Incorrect excerpt in homepage blocks

### ISSUE THREAD

**Issue by goulvench** [sudweb/2012#70]
Both "Actualité" and "Programme" excerpts are incorrect, though clicking through leads to the right page. Plus, there should be a link to the post instead of "[...]".

**Comment by thom4parisot** [comment]
I propose to postpone the [...] improvement: it is due to automatic truncation.
It is best for us to have a manual content.

**Comment by desbenoit** [comment]
ok.

**Comment by goulvench** [comment]
Marked as improvement now that the excerpt text is correct and we only need to improve the "read more" functionality. Actually, there's code on the Codex that can do just that kind of thing, we can just copy-paste when we've 5 minutes.
http://codex.wordpress.org/Function_Reference/the_excerpt

**Comment by thom4parisot** [comment]
OK so moved to the next milestone.

**Comment by thom4parisot** [comment]
I guess we're done on this one.
