### ISSUE TITLE
Reuse sponsor page layout for sponsor block

### ISSUE THREAD

**Issue by goulvench** [sudweb/2012#73]
The current sponsor presentation at the bottom of the page is not very readable, since we don't have the right image size. Reusing the styles on the sponsor page will be the fastest solution.

**Comment by thom4parisot** [comment]
Is it something different than #59?

**Comment by DirtyF** [comment]
We have to display sponsors at different sizes : 

150px wide for gold sponsors
100px wide for silver sponsors

It implies defining a new image size in the functions.php and updating the loop ?

**Comment by thom4parisot** [comment]
Totally. We could do programmatic size, like
add_thumbnail_size('sponsor-gold', )

So as it remains convienient to use in templates.

On Sat, Mar 10, 2012 at 3:36 PM, Frank Taillandier <
reply@reply.github.com

> wrote:
> 
> We have to display sponsors at different sizes :
> 
> 150px wide for gold sponsors
> 100px wide for silver sponsors
> 
> It implies defining a new image size in the functions.php and updating the
> loop ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/73#issuecomment-4434551

## 

_Thomas PARISOT_
Conseil, dveloppement et performances Web
http://case.oncle-tom.net/  @oncletom http://twitter.com/oncletom
Mobile : +336 08 40 35 49

**Comment by goulvench** [comment]
In [a patch](https://github.com/goulvench/wp-sudweb-theme/commit/a001b00529bfcc417a749f5f8cd0094b52ebe3c8) I created sponsor-logo-or and sponsor-logo-argent sizes, and gave each the appropriate dimensions. The template listing sponsors at the bottom of the page calls the_post_thumbnail('sponsor-logo-'.$type->slug) and it worked as expected, what more do you need?

**Comment by thom4parisot** [comment]
I think we are okay on this point. Are you okay with it @DirtyF?

**Comment by DirtyF** [comment]
I completely agree with you guys, let's close this issue.
