### ISSUE TITLE
Header : mettre le fond jaune pour le call to action, utiliser le fond blanc pour la date

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#75]

**Comment by desbenoit** [comment]
Oh ? Pourquoi ?

**Comment by goulvench** [comment]
On s'est rendus compte que le call-to-action était moins visible que la date, et on s'est dit que c'était pas très logique. Si tu as une autre proposition, n'hésite pas !

**Comment by desbenoit** [comment]
Ah. J'avais regardé les %  de contrastes pour faire cela. Mais si ce n'est pas ok, pas de soucis.
