### ISSUE TITLE
Use speaker image if a talk has no image

### ISSUE THREAD

**Issue by goulvench** [sudweb/2012#78]
On pages listing talks

**Comment by thom4parisot** [comment]
Is it mandatory for launch?

**Comment by desbenoit** [comment]
Nope but we have to supress test images

**Comment by thom4parisot** [comment]
It's already planned for website launch. I'll merge that right now.

**Comment by thom4parisot** [comment]
I broadened the way the thumbnail is retrieved.

The good news: it is transparently applied, and also on talk single page.
It avoids the `if (has_post_thumbnail())` thingy.

**Comment by goulvench** [comment]
## Even better, thanks!

Goulven Champenois

On Sun, Mar 11, 2012 at 1:00 AM, Oncle Tom <
reply@reply.github.com
