### ISSUE TITLE
Créer un style pour les liens “Inscrivez-vous” dans les pages

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#80]

**Comment by thom4parisot** [comment]
Why not reusing the `.cta` class?

**Comment by DirtyF** [comment]
beware of the `.cta` class, it's floating right and cannot be used inline.

**Comment by thom4parisot** [comment]
So we could use .cta-inline combined to .cta, to cancel float and fitting
our needs?

2012/3/10 Frank Taillandier <
reply@reply.github.com

> beware of the .cta class, it's floating right and cannot be used inline.
> 
> 2012/3/11 Oncle Tom <
> reply@reply.github.com
> 
> > Why not reusing the `.cta` class?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/sudweb/wp-sudweb-theme/issues/80#issuecomment-4435431
> 
> ## 
> 
> Frank Taillandier
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sudweb/wp-sudweb-theme/issues/80#issuecomment-4435605

## 

_Thomas PARISOT_
Conseil, dveloppement et performances Web
http://case.oncle-tom.net/  @oncletom http://twitter.com/oncletom
Mobile : +336 08 40 35 49

**Comment by goulvench** [comment]
I made changes so that we can start using `.cta` in page content, it won't float or clear stuff. It doesn't stand out much though.

**Comment by thom4parisot** [comment]
Need for review @DirtyF
