### ISSUE TITLE
404 for newsletter header

### ISSUE THREAD

**Issue by DirtyF** [sudweb/2012#81]
http://sudweb.fr/2011/blog/themes/sw2011/img/newsletter/top-2012bis.png

**Comment by thom4parisot** [comment]
@Aymkdn maybe you have a clue on this?

**Comment by Aymkdn** [comment]
L'aspirateur de site n'a peut tre pas tout copi s'il n'y avait pas de
lien actif. Regardez dans /2011/old/blog/.... si vous trouvez ce que vous
voulez.
Je suis en dplacement sans ordi pour le weekend.

Envoy depuis mon tlphone
Le 9 mars 2012 17:35, "Oncle Tom" <
reply@reply.github.com>
a crit :

**Comment by DirtyF** [comment]
Trouvé !

**Comment by DirtyF** [comment]
updated the mailchimp template, waiting for the pull.

**Comment by thom4parisot** [comment]
Already pulled it. Pushed it live.

**Comment by desbenoit** [comment]
? Allo ?

**Comment by Aymkdn** [comment]
Voilà j'ai copié le répertoire ~/www/2011/old/blog/themes/sw2011/img vers ~/www/2011/blog/themes/sw2011/img

Donc le lien refonctionne.

**Comment by thom4parisot** [comment]
Donc on peut fermer.
