### ISSUE TITLE
Smaller logos for silver

### ISSUE THREAD

**Issue by rudyrigot** [sudweb/2012#85]
It is in the contract with our sponsors, so i think we'll get some shit if it's not straight.

**Comment by thom4parisot** [comment]
@goulvench did the job. Please review it on the frontpage for example.

**Comment by goulvench** [comment]
In addition, gold sponsors have larger padding values between logo and

## border, to make them stand out more.

Goulven Champenois

On Sun, Mar 11, 2012 at 1:01 AM, Oncle Tom <
reply@reply.github.com

**Comment by thom4parisot** [comment]
IMHO we can close this issue.
